name: pr-validation-wf
on:
  pull_request:
    branches:
      - develop
jobs:
  Linting-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Linting of HTML and CSS Files
        run: |
          npx htmlhint "**/*.html"
          npx htmlhint "**/*.css"
  Build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build using Parcel 
        run: npx parcel build "./src/index.html" --dist-dir "./dev" --public-url "./"